<a href="https://colab.research.google.com/github/JoaoVictorEng01/Desafio-5-Ci-ncia-de-dados/blob/main/Desafio_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**5° Desafio - Ciência de dados**

*Aluno: João Victor Silva Soares*

*CPF: 613995933-07*

**DESAFIO PROPOSTO**

O gerente te apresentou uma planilha da situação atual dos clientes do banco em alguns estados do nordeste. Mas, como um bom cientista de dados sabe, nem tudo são flores. Os dados, como petróleo bruto, precisam ser refinados para procedimentos posteriores! Nesse contexto, você, como analista contratado, tem a função de interpretar e apresentar insights para o gerente.

*1. Substituir o cabeçalho por palavras em letras maiúsculas;* ✅

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('Planilha do desafio 5 - Ciência de dados - Relatório do Banco x.csv')
data.columns = data.columns.str.upper()
data.head()

,ID,PONTOS,ESTADO,GENERO,IDADE,BENS,SALDO NA CONTA,PRODUTO,POSSUI CARTAO,ATIVO,SALARIO,SAIU
0,1,619,BA,Feminino,42,2,0,1,1,1,10134888.0,1
1,2,608,CE,Feminino,41,1,8380786,1,0,1,11254258.0,0
2,3,502,BA,Feminino,42,8,1596608,3,1,0,11393157.0,1
3,4,699,BA,Feminino,39,1,0,2,0,0,9382663.0,0
4,5,850,CE,Feminino,43,2,12551082,1,1,1,790841.0,0

*2. Corrigir os dados faltantes e preencher as lacunas com valores adequados*  ✅

In [ ]:
data.isnull().sum()
# média para colunas numéricas e moda para colunas categóricas
for column in data.columns:
    if data[column].dtype == 'object':
        data[column].fillna(data[column].mode()[0], inplace=True)
    else:
        data[column].fillna(data[column].mean(), inplace=True)
data.head(100)

,ID,PONTOS,ESTADO,GENERO,IDADE,BENS,SALDO NA CONTA,PRODUTO,POSSUI CARTAO,ATIVO,SALARIO,SAIU
0,1,619,BA,Feminino,42,2,0,1,1,1,10134888.0,1
1,2,608,CE,Feminino,41,1,8380786,1,0,1,11254258.0,0
2,3,502,BA,Feminino,42,8,1596608,3,1,0,11393157.0,1
3,4,699,BA,Feminino,39,1,0,2,0,0,9382663.0,0
4,5,850,CE,Feminino,43,2,12551082,1,1,1,790841.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,97,515,CE,Masculino,35,10,17627395,1,0,1,12127778.0,0
96,98,773,CE,Masculino,41,9,10282744,1,0,1,6459525.0,0
97,99,814,CE,Masculino,29,8,970864,2,1,1,19727613.0,0
98,100,710,CE,Masculino,22,8,0,2,0,0,9964504.0,0
99,101,413,MA,Masculino,34,9,0,2,0,0,653418.0,0

*3. Eliminar os outliers, atribuindo no lugar deles os valores adequados*

In [ ]:
threshold = 3
numeric_cols = data.select_dtypes(include=[np.number]).columns
for col in numeric_cols:
    col_zscore = (data[col] - data[col].mean()) / data[col].std()
    outliers = np.abs(col_zscore) > threshold
    mean_value = data[col].mean()
    if pd.api.types.is_integer_dtype(data[col]):
        mean_value = int(mean_value)
    data.loc[outliers, col] = mean_value

data.head(100)

,ID,PONTOS,ESTADO,GENERO,IDADE,BENS,SALDO NA CONTA,PRODUTO,POSSUI CARTAO,ATIVO,SALARIO,SAIU
0,1,619,BA,Feminino,42,2,0,1,1,1,10134888.0,1
1,2,608,CE,Feminino,41,1,8380786,1,0,1,11254258.0,0
2,3,502,BA,Feminino,42,8,1596608,3,1,0,11393157.0,1
3,4,699,BA,Feminino,39,1,0,2,0,0,9382663.0,0
4,5,850,CE,Feminino,43,2,12551082,1,1,1,790841.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,97,515,CE,Masculino,35,10,17627395,1,0,1,12127778.0,0
96,98,773,CE,Masculino,41,9,10282744,1,0,1,6459525.0,0
97,99,814,CE,Masculino,29,8,970864,2,1,1,19727613.0,0
98,100,710,CE,Masculino,22,8,0,2,0,0,9964504.0,0
99,101,413,MA,Masculino,34,9,0,2,0,0,653418.0,0

*4. Eliminar os duplicados, para garantir a unicidade das informações*

In [ ]:
data.drop_duplicates(inplace=True)

*5. Substituir os NANs por valores adequados*

Já concluido ✅

*6. Corrigir os dados categóricos*

In [ ]:
data['GENERO'] = data['GENERO'].replace({'Mas': 'Masculino', 'Fem': 'Feminino'})

In [ ]:
# Salvar a planilha limpa
cleaned_file_path = 'Planilha_do_desafio_5_limpa.csv'
data.to_csv(cleaned_file_path, index=False)
cleaned_file_path

'Planilha_do_desafio_5_limpa.csv'